### ISSUE TITLE
Allow for multiple models

### ISSUE THREAD

**Issue by kevinsteger** [creme-ml/chantilly#3]
to define my_model:
requests.post('http://localhost:5000/api/**my_model**', data=dill.dumps(model))

make predictions to my_model:
requests.post('http://localhost:5000/api/**my_model**/predict', json={...

etc.

**Comment by MaxHalford** [comment]
That's an interesting proposal. Have you got a valid use-case for this? I would like to do something like this, but I think it's important that there's a default behavior if no model name is provided. Maybe the latest one should be used?

On a side-note, if we are going to store multiple models, we need to improve the storage system. Either we go with SQLite, either we continue with the [shelve](https://docs.python.org/3/library/shelve.html) module but add some tooling.

**Comment by kevinsteger** [comment]
Our use for the models is in advertising.  Our environment supports any engineer to be able to propose a model for production.  We typically run model vs. model in a champion challenger model for 24 hours and observe the results.  Having a model server that hosts multiple models would be ideal.

**Comment by MaxHalford** [comment]
> Our use for the models is in advertising. Our environment supports any engineer to be able to propose a model for production.

Ok nice. I was initially thinking of doing this transparently, by uploading an ensemble model to chantilly. For example in creme there is a `SuccessiveHalvingClassifier` model which you provide with a list of models. This wrapper model will transparently take care of selecting the best model and discarding the worst ones. 

> We typically run model vs. model in a champion challenger model for 24 hours and observe the results.

I didn't know about the champion challenger scheme, but it makes complete sense. I'll try to get something done soon.

> Please consider REDIS support for the storage system.

I will!

**Comment by MaxHalford** [comment]
Okay @kevinsteger I added support for multiple models. You can see the relevant documentation [here](https://github.com/creme-ml/chantilly#using-multiple-models). Tell me what you think, the API is not in stone yet so I can make changes.

**Comment by kevinsteger** [comment]
Looks good to me.  I will give it a try ASAP thanks for being so responsive!
