### ISSUE TITLE
move default error log location

### ISSUE THREAD

**Issue by kevinsteger** [creme-ml/chantilly#8]
I went looking for errors and found them in the /var/log/syslog

Please make /var/log/chantilly/error.log or something similar to make it easy to find.  

Thank you!

**Comment by MaxHalford** [comment]
Nice one I didn't think about logging. I don't have a lot of experience with this so feel free to make suggestions :)

**Comment by MaxHalford** [comment]
Hey @kevinsteger. So I checked and it seems that `/var/log/syslog` is a sensible default. I have however added an [example](https://github.com/creme-ml/chantilly#configuration-handling) in the documentation to show how to configure the logging to suit your needs. Essentially to need to use a [`FileHandler`](https://docs.python.org/3/library/logging.handlers.html#logging.FileHandler) and set the `filename` parameter to `/var/log/chantilly/error.log`.

I hope this is good enough for you!
